sudo: required
language: generic

services:
- docker

script:
  - docker build --tag loadbalancing-verification-service --tag loadbalancing-verification-service:latest --tag loadbalancing-verification-service:$(date "+%d-%m-%Y_%H-%M-%S") .'
  - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
  - docker push loadbalancing-verification-service