sudo: required
language: generic

services:
- docker

script:
  - docker build --tag 21stio/nodejs-loadbalancing-verification-service --tag 21stio/nodejs-loadbalancing-verification-service:latest --tag 21stio/nodejs-loadbalancing-verification-service:$(date "+%d-%m-%Y_%H-%M-%S") .
  - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
  - docker push 21stio/nodejs-loadbalancing-verification-service