sudo: required
language: generic

services:
- docker

script:
  - docker build --tag ${REGISTRY_USERNAME}/nodejs-loadbalancing-verification-service --tag ${REGISTRY_USERNAME}/nodejs-loadbalancing-verification-service:latest --tag ${REGISTRY_USERNAME}/nodejs-loadbalancing-verification-service:$(date "+%d-%m-%Y_%H-%M-%S") .
  - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
  - docker push ${REGISTRY_USERNAME}/nodejs-loadbalancing-verification-service