version: "2"
services:
  base-application:
    build: .
    environment:
      - APPLICATION_PORT=9000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - 9000:9000
  base-redis:
    image: redis
    ports:
      - 6379

  development-application:
    extends: base-application
    links:
      - development-redis:redis
    volumes:
      - .:/opt/application
  development-redis:
    extends: base-redis